Herald

diff --git a/container/Containerfile b/container/Containerfile
--- a/container/Containerfile
+++ b/container/Containerfile
@@ -8,36 +8,39 @@ ARG DISTRO_VARIANT=3.21
 FROM docker.io/nfrastack/container-base:${DISTRO}_${DISTRO_VARIANT}
 
 LABEL \
-  org.opencontainers.image.title="DNS Companion" \
+  org.opencontainers.image.title="Herald" \
   org.opencontainers.image.description="Manage DNS records based on DNS servers based on events from Docker or Traefik" \
-  org.opencontainers.image.url="https://hub.docker.com/r/nfrastack/dns-companion" \
-  org.opencontainers.image.documentation="https://github.com/nfrastack/dns-companion/blob/main/README.md" \
-  org.opencontainers.image.source="https://github.com/nfrastack/dns-companion.git" \
+  org.opencontainers.image.url="https://hub.docker.com/r/nfrastack/herald" \
+  org.opencontainers.image.documentation="https://github.com/nfrastack/herald/blob/main/README.md" \
+  org.opencontainers.image.source="https://github.com/nfrastack/herald.git" \
   org.opencontainers.image.authors="Nfrastack <code@nfrastack.com>" \
   org.opencontainers.image.vendor="Nfrastack <https://www.nfrastack.com>" \
   org.opencontainers.image.licenses="BSD-3-Clause"
 
-ARG DC_VERSION
-ARG GOLANG_VERSION
+ARG HERALD_VERSION \
+    GOLANG_VERSION \
+    YQ_VERSION
 
 ENV CONTAINER_ENABLE_SCHEDULING=TRUE \
-    DC_VERSION=${DC_VERSION:-"dev"} \
-    DC_USER=dc \
-    DC_GROUP=dc \
-    IMAGE_VERSION=${DC_VERSION} \
-    IMAGE_NAME="nfrastack/dns-companion" \
-    IMAGE_REPO_URL="https://github.com/nfrastack/dns-companion"
+    HERALD_VERSION=${HERALD_VERSION:-"2.0.0"} \
+    HERALD_USER=herald \
+    HERALD_GROUP=herald \
+    YQ_VERSION=${YQ_VERSION:-"v4.45.4"} \
+    YQ_REPO_URL=${YQ_REPO_URL:-"https://github.com/mikefarah/yq"} \
+    IMAGE_VERSION=${HERALD_VERSION} \
+    IMAGE_NAME="nfrastack/herald" \
+    IMAGE_REPO_URL="https://github.com/nfrastack/herald"
 
-COPY / /usr/src/dns-companion
+COPY / /usr/src/herald
 
 RUN echo "" && \
-    DC_BUILD_DEPS_ALPINE=" \
-                                go \
+    HERALD_BUILD_DEPS_ALPINE=" \
+                                #go \
                                 make \
                           " \
                           && \
     \
-    DC_BUILD_DEPS_DEBIAN=" \
+    HERALD_BUILD_DEPS_DEBIAN=" \
                                 make \
                           " \
                           && \
@@ -47,41 +50,48 @@ RUN echo "" && \
     \
     mkdir -p /usr/src/container/ && \
     cp \
-        /usr/src/dns-companion/{CHANGELOG.md,LICENSE,README.md} \
+        /usr/src/herald/{CHANGELOG.md,LICENSE,README.md} \
                                                 /usr/src/container/ \
                                                 && \
     \
     container_build_log && \
     \
-    create_user "${DC_USER}" 1000 "${DC_GROUP}" 1000 /dev/null && \
+    create_user "${HERALD_USER}" 1000 "${HERALD_GROUP}" 1000 /dev/null && \
     package update && \
     package upgrade && \
     package install \
-                    DC_BUILD_DEPS \
+                    HERALD_BUILD_DEPS \
                     && \
     \
-    case "$(container_info distro)" in \
-        "debian" ) \
-            mkdir -p /usr/local/go ; \
-            GOLANG_VERSION=${GOLANG_VERSION:-"$(curl -sSL https://golang.org/VERSION?m=text | head -n1 | sed "s|^go||g")"} ; \
-            curl -sSLk  https://dl.google.com/go/go${GOLANG_VERSION}.linux-$(dpkg --print-architecture).tar.gz | tar xvfz - --strip 1 -C /usr/local/go ; \
-            ln -sf /usr/local/go/bin/go /usr/local/bin/ ; \
-            ln -sf /usr/local/go/bin/godoc /usr/local/bin/ ; \
-            ln -sf /usr/local/go/bin/gfmt /usr/local/bin/ ;  \
-        ;; \
-    esac ; \
+    mkdir -p /usr/local/go ; \
+    GOLANG_VERSION=${GOLANG_VERSION:-"$(curl -sSL https://golang.org/VERSION?m=text | head -n1 | sed "s|^go||g")"} ; \
+    curl -sSLk https://dl.google.com/go/go${GOLANG_VERSION}.linux-$(container_info arch alt).tar.gz | tar xvfz - --strip 1 -C /usr/local/go ; \
+    ln -sf /usr/local/go/bin/go /usr/local/bin/ ; \
+    ln -sf /usr/local/go/bin/godoc /usr/local/bin/ ; \
+    ln -sf /usr/local/go/bin/gfmt /usr/local/bin/ ;  \
     \
-    cd /usr/src/dns-companion && \
+    clone_git_repo \
+                    "${YQ_REPO_URL}" \
+                    "${YQ_VERSION}" \
+                    /usr/src/yq && \
     \
-    case "$(container_info arch)" in \
-        aarch64) \
-            GOARCH=amd64 ; \
-        ;; \
-        x86_64) \
-            GOARCH=amd64 ; \
+    go build \
+                -ldflags "\
+                            -s \
+                            -w \
+                            -X github.com/mikefarah/yq/v4/version.Version=${YQ_VERSION} \
+                          " \
+                -o /usr/local/bin/yq \
+                && \
+    \
+    cd /usr/src/herald && \
+    \
+    case "$(container_info arch alt)" in \
+        amd64 | arm64) \
+            : ; \
         ;; \
         * ) \
-            echo >&2 "Error: unsupported architecture ($(container_info arch))" ; \
+            echo >&2 "Error: unsupported architecture ($(container_info arch alt))" ; \
             exit 1 ; \
         ;; \
     esac ; \
@@ -90,11 +100,11 @@ RUN echo "" && \
     make install && \
     \
     cp -aR \
-                /usr/src/dns-companion/docker/rootfs/*  \
+                /usr/src/herald/container/rootfs/*  \
             / && \
     \
     package remove \
-                    DC_BUILD_DEPS \
+                    HERALD_BUILD_DEPS \
                     && \
     package cleanup && \
     rm -rf \
